
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: {{ .Values.containerImage }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          ports:
            - containerPort: 8000
          env:
            - name: PYTHON_ENTRYPOINT
              value: "main.py"
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: supabase-url
            - name: SUPABASE_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: supabase-service-key
            
